version: '3'
services:
  laravel-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      - APP_NAME=Laravel
      - APP_ENV=local
        - APP_KEY=base64:q
        - APP_DEBUG=true
        - APP_URL=http://localhost
        - LOG_CHANNEL=stack
        - DB_CONNECTION=mysql
        - DB_HOST=mysql
        - DB_PORT=3306
        - DB_DATABASE=laravel
        - DB_USERNAME=laravel
        - DB_PASSWORD=laravel
        - BROADCAST_DRIVER=log
        - CACHE_DRIVER=file
        - QUEUE_CONNECTION=sync
        - SESSION_DRIVER=file
        - SESSION_LIFETIME=120
        - REDIS_HOST=
        - REDIS_PASSWORD=null
        - REDIS_PORT=6379
        - MAIL_DRIVER=smtp
        - MAIL_HOST=mailhog
        - MAIL_PORT=1025
        - MAIL_USERNAME=null
        - MAIL_PASSWORD=null
        - MAIL_ENCRYPTION=null
        - MAIL_FROM_ADDRESS=null
        - MAIL_FROM_NAME="${APP_NAME}"
        - AWS_ACCESS_KEY_ID=
        - AWS_SECRET_ACCESS_KEY=
        - AWS_DEFAULT_REGION=us-east-1
        - AWS_BUCKET=
        - PUSHER_APP_ID=
        - PUSHER_APP_KEY=
        - PUSHER_APP_SECRET=
        - PUSHER_APP_CLUSTER=mt1
        - MIX_PUSHER_APP_KEY="${PUSHER_APP_KEY}"
        - MIX_PUSHER_APP_CLUSTER="${PUSHER_APP_CLUSTER}"

